### ISSUE TITLE
Transformer 不能正确的 解析 require('package')

### ISSUE THREAD

**Issue by huiop368** [weexteam/weex-transformer#1]
``` html
  <template>
  <div>
    <cnx-white-space></cnx-white-space>
    <text>Hello</text>
  </div>
</template>

<script>
  require("@ali/cnx-component");   

  // 是否这里写法上有问题， 该不会要 写成  require('path/node_modules/@ali/cnx-component') 之类的吧???
</script>
```

@ali/cnx-component 是我们自己发布的一个 weex component 包， 已经发布的.

我需要运行 transformer.transform('name', '上面的source code'),  目前发现转化后的 result 不含 '@ali/cnx-component'里面的widget.

请问是否支持？

**Comment by songsiqi** [comment]
@huiop368 用 weex-loader 吧。weex-transformer 的 require 只支持 js 的加载，对于 component，最好使用 weex-loader。

**Comment by huiop368** [comment]
@songsiqi  谢谢回复， 怪不得，看了下 weex-transformer 码， 发现用brower 加载 一些js第三方库，估计是支持不了component...

好的，那我试试 weex-loader...
